### ISSUE TITLE
Update how to contribute link

### ISSUE THREAD

**Issue by pioterj** [gradle-guides/running-webpack-with-gradle#3]
How to contribute section has an old link to https://github.com/gradle-guides/running-webpack-with-gradle instead of https://github.com/gradle-guides/running-webpack-with-gradle. Not a big deal since there is a redirect in place but it can be a bit confusing. The link is autogenerated with `include::contribute[]`. 

@ysb33r Why it doesn't generate the current link?

**Comment by ysb33r** [comment]
https://github.com/gradle-guides/running-webpack-with-gradle/blob/master/build.gradle#L11

I don't think @eriwen update the link in `build.gradle`. I

**Comment by ysb33r** [comment]
Fixed it on `master`.

**Comment by pioterj** [comment]
Thanks, @ysb33r!
