### ISSUE TITLE
Make title consistent between home page and this guide page 

### ISSUE THREAD

**Issue by pioterj** [gradle-guides/running-webpack-with-gradle#4]
Currently on https://gradle.org/guides/ the title is "Bundling JavaScript with Webpack" but when you open it the title is "Running Webpack with Gradle". @eriwen Which one is correct? I guess the latter?

**Comment by eriwen** [comment]
This is fixed by gradle/dotorg-site@c9ad30206d20fa7356a5cc5edc337e649029f23f
