### ISSUE TITLE
Typo on section 4.1 to run webpack 

### ISSUE THREAD

**Issue by tchau** [gradle-guides/running-webpack-with-gradle#9]
The code on step 4.1 has a typo (https://guides.gradle.org/running-webpack-with-gradle/):

    commandLine "$projectDir/node_modules/.bin/webpack", "app/index.js", "$buildDir/js/bundle.js"

needs to be 

    commandLine "$projectDir/node_modules/.bin/webpack", "app/index.js", "-o=$buildDir/js/bundle.js"

The "-o" flag is missing which causes webpack to think $buildDir/js/bundle.js is an input and it will crash since it does not exist

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #266](https://github.com/gradle/guides/issues/266) via [**ZenHub**](https://www.zenhub.com/)
